export {
  getCellRanges,
  getRangeAsCsv,
  searchData,
  getAllObjects,
  setCellRange,
  clearCellRange,
  copyTo,
  modifySheetStructure,
  modifyWorkbookStructure,
  resizeRange,
  modifyObject,
  getWorksheetById,
  type CellData,
  type CellStyle,
  type CellInput,
  type GetCellRangesResult,
  type GetRangeAsCsvResult,
  type SearchDataResult,
  type SearchMatch,
  type GetAllObjectsResult,
  type ExcelObject,
  type SetCellRangeResult,
  type ClearCellRangeResult,
  type CopyToResult,
  type ModifySheetStructureResult,
  type ModifyWorkbookStructureResult,
  type ResizeRangeResult,
  type ModifyObjectResult,
  type WorksheetInfo,
} from "./api";
